apiVersion: hyperfoil.io/v1alpha2
kind: Hyperfoil
metadata:
  name: hyperfoil-cluster
  namespace: hyperfoil
spec:
  route:
    host: ${HYPERFOIL_SERVER_URL}
  agentDeployTimeout: 120000
  version: latest
